// common
import "./components/common/TrnLogo.jsx";
import "./components/common/TrnHeader.jsx";
import "./components/common/TrnSbProfile";
import "./components/common/TrnSbFixturesAndResults";
import "./components/common/TrnStandings";
import "./components/common/TrnStandingsRow";
import "./components/common/TrnSidebar.jsx";
import "./components/common/TrnLayout.jsx";
import "./components/common/TrnFooter.jsx"
import "./components/common/TrnWelcome.jsx"

// posts
import "./components/posts/CustomEmbedlyURL.jsx";
import "./components/posts/PostsLinkBody.jsx";
import "./components/posts/PostsVideoBody.jsx";
import "./components/posts/PostsMatchBody.jsx";
import "./components/posts/PostsMatchIdField.jsx";
import "./components/posts/PostsCategoriesSelector.jsx";
import "./components/posts/PostsCategoriesSelectorWrapper.jsx";
import "./components/posts/TrnPostsItem.jsx";
import "./components/posts/TrnPostsListHeader.jsx";
import "./components/posts/TrnPostsList.jsx";
import "./components/posts/TrnPostsCommentsThread.jsx";
import "./components/posts/TrnPostsPage.jsx";
import "./components/posts/TrnPostsNewForm.jsx";
import "./components/posts/TrnPostsHome.jsx";
import "./components/posts/TrnPostsCategories.jsx";
import "./components/posts/PostsSingle.jsx";

// users
import "./components/users/TrnUsersAccountMenu.jsx";
import "./components/users/TrnUsersMenu.jsx";

// categories
import "./components/categories/TrnCategoriesList.jsx";
import "./components/categories/TrnCategoriesNewForm.jsx";
import "./components/categories/TrnCategoriesEditForm.jsx";
import "./components/categories/CategoriesBar.jsx";
import "./components/categories/CategoriesAdminPage.jsx";
import "./components/categories/CategoriesAdminList.jsx";
import "./components/categories/CategoriesAdminRemoteList.jsx";
import "./components/categories/CategoriesVisibilityButton.jsx";
import "./components/categories/CategoriesCompetitionsNewButton.jsx";
import "./components/categories/CategoriesCompetitionsEditButton.jsx";
import "./components/categories/CategoriesAttachedTeams.jsx";
