import "./callbacks.js"
import "./emails.js"
import "./custom_fields.js"
import "./intl.js"
import "./groups.js"

import "./components/TrnLogo.jsx"
import "./components/TrnCategoriesList.jsx"
import "./components/TrnLayout.jsx"
import "./components/TrnPostsItem.jsx"
import "./components/TrnPostsList.jsx"
import "./components/TrnPostsPage.jsx"
import "./components/TrnUsersMenu.jsx"
import "./components/MatchIdField.jsx"
import "./components/post-types/MatchBody.jsx"

import "./components/admin/AdminPage.jsx"
import "./components/admin/AdminCategoriesList.jsx"
import "./components/admin/AdminCategoriesRemoteList.jsx"
import "./components/admin/CategoriesNewFormPrefilled.jsx"
import "./components/admin/CategoriesActivityButton.jsx"
import "./components/admin/CategoriesVisibilityButton.jsx"
import "./components/admin/CategoriesCompetitionsNewButton.jsx"
import "./components/admin/CategoriesCompetitionsEditButton.jsx"

import "./routes.jsx"
